name: ci

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install
      run: npm i
    - name: Build
      run: npx ng build --configuration "production" --base-href "https://makimenko.github.io/vect/" --output-path ./dist/gh-pages-deploy
    - name: Upload
      uses: actions/upload-artifact@v1
      with:
        name: spa
        path: ./dist/gh-pages-deploy
  publish:
    runs-on: ubuntu-latest
    needs: [build]
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Download
        uses: actions/download-artifact@v1
        with:
          name: spa
          path: dist
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
